### ISSUE TITLE
Installing from requirements.txt fails

### ISSUE THREAD

**Issue by anderhos** [basel-a/SMET#2]
Hi,

I am having trouble installing from `requirements.txt`.

The issue seems to originate from incompatible transitive dependencies.

Running `pip install -r requirements.txt`, I am getting the following output:

![Screenshot 2024-01-02 at 16 47 25](https://github.com/basel-a/SMET/assets/54975483/74fbbf3f-765f-4337-bcfc-ed60d51404ed)
![Screenshot 2024-01-02 at 16 48 20](https://github.com/basel-a/SMET/assets/54975483/27f3bf17-155e-4528-ac8f-b1ea75dd45c0)

I am using Python 3.8.18 as specified in `README`. The OS is Ubuntu 22.04.3 LTS.

Any ideas on how to fix this?

Perhaps uploading a frozen environment may be helpful for solving the issue? 

For example, `pip freeze > requirements-frozen.txt`.

**Comment by basel-a** [comment]
I just uploaded requirements-frozen.txt, I hope it will help.

**Comment by anderhos** [comment]
Thank you!
For me, the following steps worked:

1. Creating a new virtual environment with Python 3.9
2. Setting environment variables as done [here](https://github.com/PyMySQL/mysqlclient/issues/584#issuecomment-1537354773)
3. Installing packages from requirements-frozen.txt
