### ISSUE TITLE
Manually annotated dataset

### ISSUE THREAD

**Issue by anderhos** [basel-a/SMET#3]
Hi again,

You mention introducing a manually annotated dataset in the [paper](https://link.springer.com/chapter/10.1007/978-3-031-37586-6_15). Could you please share this?

Getting access to the data would be very helpful in reproducing and building upon your work.

**Comment by basel-a** [comment]
I just uploaded the data. Good luck!

**Comment by anderhos** [comment]
Thanks a lot!
