### ISSUE TITLE
Request to add a license to the repository

### ISSUE THREAD

**Issue by anderhos** [basel-a/SMET#5]
Thanks again for sharing the project @basel-a 

I noticed that this repository currently doesn’t have a license.  With a license, it would be easier for others who are interested in contributing to or using this project in their own work.

Would it be possible to add a license to the repository? If you need a suggestion, popular open-source licenses like the MIT License might be a good option. See e.g this [tutorial](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) on how to add it.

**Comment by basel-a** [comment]
Hello Anders,

Thanks for your interest. I added a license to the repository.

Best regards,
Basel
________________________________
From: Anders Mølmen Høst ***@***.***>
Sent: Thursday, September 12, 2024 9:45 AM
To: basel-a/SMET ***@***.***>
Cc: Abdeen, Basel ***@***.***>; Mention ***@***.***>
Subject: [basel-a/SMET] Request to add a License to the Repository (Issue #5)


Thanks again for sharing the project @basel-a<https://github.com/basel-a>

I noticed that this repository currently doesn’t have a license. With a license, it would be easier for others who are interested in contributing to or using this project in their own work.

Would it be possible to add a license to the repository? If you need a suggestion, popular open-source licenses like the MIT License might be a good option. See e.g this tutorial<https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository> on how to add it.
